dataset:
  train_file_path: "data/processed/train_val_final.parquet"
  test_file_path: "data/processed/test_final.parquet"
  target_label: isFraud
  categorical_features: [
        "ProductCD",
        "card4",
        "card6",
        "addr1",
        "P_emaildomain",
        "R_emaildomain",
        "M1",
        "M2",
        "M3",
        "M4",
        "M5",
        "M6",
        "M7",
        "M8",
        "M9",
        "id_12",
        "id_15",
        "id_30",
        "id_31",
        "id_33",
        "id_34",
        "id_35",
        "id_36",
        "id_37",
        "id_38",
        "DeviceType",
        "DeviceInfo"
    ]
  non_negative_features:
    - TransactionAmt
  non_negative_prefixes:
    - C
    - D
  perturbable_categorical_features:
  - ProductCD
  - card4
  - card6
  - addr1
  perturbable_numerical_features:
  - TransactionAmt
  - dist1

model:
  architecture: CatBoost
  file_path: "data/models/catboost_fraud_model_lr0.01_depth10_2026-03-20_192829.cbm"
  metadata:
    name: "CatBoost Fraud Model"

explainer:
  method: KernelSHAP
  params:
    background_samples: 100
    background_strategy: kmeans
    kmeans_impute_strategy: median
    kmeans_n_init: 10
    kmeans_max_iter: 300
    n_samples: 2000
    random_seed: 42


perturbations:
  - name: DirectionalDrift
    n_perturbations: 20
    random_seed: 42
    params:
      drift_factor: 0.2
      drift_factor_range: [0.2, 0.4]
      target_features: ["TransactionAmt"]

metrics:
  - name: RelativeInputStability
  - name: RankBiasedOverlap
  - name: SignConsistencyRate
  - name: GlobalConsistencyMetric
  - name: GlobalSufficiencyMetric

experiment:
  name: DissertationExperiment_KernelSHAP_TP_Drift
  type: DissertationExperiment
  sample_size: 500
  sample_group: TP
  random_seed: 42
  chunk_size: 25
  max_workers: 1
  resume: true
  checkpoint_dir: "results/checkpoints"
  results_dir: "results"
